name: Update Secret Variable

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-secret:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Read current version
      id: read_version
      run: |
        set -x
        current_version=${{ secrets.VERSION }}
        if [ -z "$current_version" ]; then
          current_version="0.0.0"
        fi
        echo "Current version: $current_version"
        echo "::set-output name=current_version::$current_version"

    - name: Increment version
      id: increment_version
      run: |
        set -x
        current_version=${{ steps.read_version.outputs.current_version }}
        IFS='.' read -r -a version_parts <<< "$current_version"
        echo "version_parts[0]"
        echo "version_parts[1]"
        echo "version_parts[2]"
        version_parts[2]=$((version_parts[2] + 1))
        new_version="${version_parts[0]}.${version_parts[1]}.${version_parts[2]}"
        echo "New version: $new_version"
        echo "::set-output name=new_version::$new_version"

    - name: Update secret variable
      run: |
        new_version=${{ steps.increment_version.outputs.new_version }}
        gh secret set VERSION --repo reaper256/Fluent-Test --body "${new_version}"
      env:
        GH_TOKEN: ${{ secrets.powersecret }}
